### ISSUE TITLE
Configure default environments for client

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-applications#108]
So they don't have to.  For someone unfamiliar with lightblue it is very easy to misconfigure the data management application.  Could we have optional configuration for the app on the server side that would pre-populate some environments for everybody using the app?  Probably want to have them be immutable in the client as well.

**Comment by alechenninger** [comment]
This is an interesting issue since there isn't actually a service side component to the application other than a basic HTTP server. Maybe we could do something where you can optionally bundle an environment config with the application (server side), and client-side makes an AJAX request for this config, and if found.

Also opened #105 which might be another way to improve the user experience.

**Comment by alechenninger** [comment]
I think this is a duplicate of #64 actually,

**Comment by jewzaam** [comment]
Well look at that... thanks.
