### ISSUE TITLE
Data Management: Display lightblue error responses in Response section

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-applications#66]
Right now errors returned from lightblue are not placed in the Response section of the page.  After discussing with @alechenninger, this is likely due to the change we made not long ago to return the correct HTTP codes that correspond to the response (instead of just returning 200 all the time).

Ideally, we should display any JSON response returned from the lightblue services, and also gracefully handle the case when the app server returns an error in HTML format (maybe strip out the HTML and wrap it in a JSON structure so the message can be displayed in the Response section).

**Comment by alechenninger** [comment]
To clarify for anyone wondering, this is different from #65 in that #65 is referring to when the app cannot communicate with lightblue at all (due to auth or CORS issues, for example), whereas this issue is referring to communication with lightblue that returned an error status.

**Comment by jewzaam** [comment]
This is a pretty big bug.  I'd like to prioritize it.  I'm trying to prep for a demo of lightblue with some existing clients and not having the error response is making the app very hard to use.  I have to build a curl statement to figure out why things are not working!

Having the error displayed is a requirement for this app to be useful given that the query builder is simple, allowing free-form entry.

@alechenninger how much time would this take to fix?  who knows enough about the app to take on this work?  It's not a blocker since there are other ways to do this, but it's a usability limiting issue.

**Comment by alechenninger** [comment]
I agree. It's a simple fix, I'll take care of it this weekend.
